### ISSUE TITLE
TPCx-BB benchmark query 03 fails on 16-GPU GV100 node

### ISSUE THREAD

**Issue by rfvander** [rapidsai/tpcx-bb#136] opened 2020-11-11 22:30 UTC
I am running query 03 with the default parameters for storage: DEVICE_MEMORY_LIMIT="25GB", POOL_SIZE="30GB"
I have allocated all 16 GPUs, after creating the dask cluster with: "bash cluster-startup.sh SCHEDULER". When monitoring GPU activity on the cluster after starting the query, I briefly see activity of single-digit percents on all GPUs (all have one process, except GPU 0, which has two). But in about a second the query fails, with this error message:
python tpcx_bb_query_03.py --config_file=../../benchmark_runner/benchmark_config.yaml
Using default arguments
{
  "type": "Scheduler",
  "id": "Scheduler-224dfe8e-84c1-4e6a-95f9-75e225f09315",
  "address": "tcp://10.33.14.69:8786",
  "services": {
    "dashboard": 8787
  },
  "workers": {}
}
Connected!
------------------------------------------------------------
Encountered Exception while running query
Traceback (most recent call last):
  File "/home/scratch.robv_gpu_1/apps/rapids/notebooks/xgboost/dask-xgboost/ls/envs/rapids-tpcx-bb/lib/python3.7/site-packages/xbb_tools/utils.py", line 280, in run_dask_cudf_query
    config=config,
  File "/home/scratch.robv_gpu_1/apps/rapids/notebooks/xgboost/dask-xgboost/ls/envs/rapids-tpcx-bb/lib/python3.7/site-packages/xbb_tools/utils.py", line 61, in benchmark
    result = func(*args, **kwargs)
  File "../q03/tpcx_bb_query_03.py", line 272, in main
    print("grouping complete ={}".format(len(grouped_df)))
  File "/home/scratch.robv_gpu_1/apps/rapids/notebooks/xgboost/dask-xgboost/ls/envs/rapids-tpcx-bb/lib/python3.7/site-packages/dask/dataframe/core.py", line 3525, in __len__
    return len(s)
  File "/home/scratch.robv_gpu_1/apps/rapids/notebooks/xgboost/dask-xgboost/ls/envs/rapids-tpcx-bb/lib/python3.7/site-packages/dask/dataframe/core.py", line 545, in __len__
    len, np.sum, token="len", meta=int, split_every=False
  File "/home/scratch.robv_gpu_1/apps/rapids/notebooks/xgboost/dask-xgboost/ls/envs/rapids-tpcx-bb/lib/python3.7/site-packages/dask/base.py", line 167, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/scratch.robv_gpu_1/apps/rapids/notebooks/xgboost/dask-xgboost/ls/envs/rapids-tpcx-bb/lib/python3.7/site-packages/dask/base.py", line 454, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/scratch.robv_gpu_1/apps/rapids/notebooks/xgboost/dask-xgboost/ls/envs/rapids-tpcx-bb/lib/python3.7/site-packages/distributed/client.py", line 2725, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/home/scratch.robv_gpu_1/apps/rapids/notebooks/xgboost/dask-xgboost/ls/envs/rapids-tpcx-bb/lib/python3.7/site-packages/distributed/client.py", line 1992, in gather
    asynchronous=asynchronous,
  File "/home/scratch.robv_gpu_1/apps/rapids/notebooks/xgboost/dask-xgboost/ls/envs/rapids-tpcx-bb/lib/python3.7/site-packages/distributed/client.py", line 833, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "/home/scratch.robv_gpu_1/apps/rapids/notebooks/xgboost/dask-xgboost/ls/envs/rapids-tpcx-bb/lib/python3.7/site-packages/distributed/utils.py", line 340, in sync
    raise exc.with_traceback(tb)
  File "/home/scratch.robv_gpu_1/apps/rapids/notebooks/xgboost/dask-xgboost/ls/envs/rapids-tpcx-bb/lib/python3.7/site-packages/distributed/utils.py", line 324, in f
    result[0] = yield future
  File "/home/scratch.robv_gpu_1/apps/rapids/notebooks/xgboost/dask-xgboost/ls/envs/rapids-tpcx-bb/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/home/scratch.robv_gpu_1/apps/rapids/notebooks/xgboost/dask-xgboost/ls/envs/rapids-tpcx-bb/lib/python3.7/site-packages/distributed/client.py", line 1851, in _gather
    raise exception.with_traceback(traceback)
  File "../q03/tpcx_bb_query_03.py", line 67, in pre_repartition_task
    wcs_df = cudf.read_parquet(wcs_fn, columns=wcs_cols)
  File "/home/scratch.robv_gpu_1/apps/rapids/notebooks/xgboost/dask-xgboost/ls/envs/rapids-tpcx-bb/lib/python3.7/site-packages/cudf/io/parquet.py", line 249, in read_parquet
    use_pandas_metadata=use_pandas_metadata,
  File "cudf/_lib/parquet.pyx", line 173, in cudf._lib.parquet.read_parquet
  File "cudf/_lib/parquet.pyx", line 223, in cudf._lib.parquet.read_parquet
MemoryError: std::bad_alloc: RMM failure at:/home/scratch.robv_gpu_1/apps/rapids/notebooks/xgboost/dask-xgboost/ls/envs/rapids-tpcx-bb/include/rmm/mr/device/pool_memory_resource.hpp:188: Maximum pool size exceeded

I am attaching files worker.log and scheduler.log
[worker.log](https://github.com/rapidsai/tpcx-bb/files/5527087/worker.log)
[scheduler.log](https://github.com/rapidsai/tpcx-bb/files/5527088/scheduler.log)

**Comment by beckernick** [comment] 2020-11-12 02:55
Root cause is using a dataset that converted each the raw CSV tables into very large single parquet files. Switching datasets resolves the issue. Closing

**Closed by beckernick** 2020-11-12 02:55 UTC
